package org.zeus.repository.sensor;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import org.zeus.dbo.SensorType;

import java.util.Optional;

/**
 * Spring Data JPA repository for {@link SensorType} entities.
 * Provides standard CRUD operations and custom query methods for accessing sensor type data.
 */
@Repository
public interface SensorTypeRepository extends JpaRepository<SensorType, Integer> {

    /**
     * Finds a SensorType by its unique type name.
     * This is a custom query method generated by Spring Data JPA based on the method name.
     *
     * @param typeName The unique name of the sensor type (e.g., "TEMPERATURE_AND_HUMIDITY_SENSOR").
     * @return An {@link Optional} containing the found {@link SensorType}, or an empty Optional if no matching type is found.
     */
    Optional<SensorType> findByTypeName(String typeName);
}